language: ruby
cache: bundler

rvm:
  - 2.0.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - vinh.nguyenlexuan@asnet.com.vn
    on_failure: always
    on_success: change
